/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\agree\\portal\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-1ac271fc",
    path: "/Aui/card.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ac271fc").then(next)
    },
  },
  {
    name: "v-1e750138",
    path: "/Aui/button.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e750138").then(next)
    },
  },
  {
    name: "v-42c098f8",
    path: "/Aui/badge.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42c098f8").then(next)
    },
  },
  {
    name: "v-f98a8a6a",
    path: "/Aui/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f98a8a6a").then(next)
    },
  },
  {
    path: "/Aui/index.html",
    redirect: "/Aui/"
  },
  {
    name: "v-426e5020",
    path: "/Aui/cascader.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-426e5020").then(next)
    },
  },
  {
    name: "v-610fa7ac",
    path: "/Aui/color-picker.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-610fa7ac").then(next)
    },
  },
  {
    name: "v-d76d7bfc",
    path: "/Aui/collapse.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d76d7bfc").then(next)
    },
  },
  {
    name: "v-1c27f956",
    path: "/Aui/checkbox.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c27f956").then(next)
    },
  },
  {
    name: "v-72ef0f5c",
    path: "/Aui/count-down.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72ef0f5c").then(next)
    },
  },
  {
    name: "v-655b9144",
    path: "/Aui/container.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-655b9144").then(next)
    },
  },
  {
    name: "v-f1f06980",
    path: "/Aui/date.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f1f06980").then(next)
    },
  },
  {
    name: "v-44ba1364",
    path: "/Aui/counter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44ba1364").then(next)
    },
  },
  {
    name: "v-947b41e8",
    path: "/Aui/dialog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-947b41e8").then(next)
    },
  },
  {
    name: "v-f68af38c",
    path: "/Aui/dropdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f68af38c").then(next)
    },
  },
  {
    name: "v-583b9e04",
    path: "/Aui/group.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-583b9e04").then(next)
    },
  },
  {
    name: "v-1c001824",
    path: "/Aui/input.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c001824").then(next)
    },
  },
  {
    name: "v-47c269a4",
    path: "/Aui/global-configure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47c269a4").then(next)
    },
  },
  {
    name: "v-1f9c9ee4",
    path: "/Aui/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f9c9ee4").then(next)
    },
  },
  {
    name: "v-04b9e148",
    path: "/Aui/layout.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04b9e148").then(next)
    },
  },
  {
    name: "v-2161ea60",
    path: "/Aui/i18n.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2161ea60").then(next)
    },
  },
  {
    name: "v-578e0938",
    path: "/Aui/loading.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-578e0938").then(next)
    },
  },
  {
    name: "v-7c3742c4",
    path: "/Aui/menu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c3742c4").then(next)
    },
  },
  {
    name: "v-2e9c21f8",
    path: "/Aui/message-box.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e9c21f8").then(next)
    },
  },
  {
    name: "v-2a1f7f30",
    path: "/Aui/pagination.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a1f7f30").then(next)
    },
  },
  {
    name: "v-2be82684",
    path: "/Aui/popover.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2be82684").then(next)
    },
  },
  {
    name: "v-17b12502",
    path: "/Aui/progress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17b12502").then(next)
    },
  },
  {
    name: "v-5372ac80",
    path: "/Aui/qrcode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5372ac80").then(next)
    },
  },
  {
    name: "v-1918c484",
    path: "/Aui/radio.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1918c484").then(next)
    },
  },
  {
    name: "v-53234a5c",
    path: "/Aui/rate.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53234a5c").then(next)
    },
  },
  {
    name: "v-03b7aae2",
    path: "/Aui/roll.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03b7aae2").then(next)
    },
  },
  {
    name: "v-3e83fba4",
    path: "/Aui/select.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e83fba4").then(next)
    },
  },
  {
    name: "v-11ce024c",
    path: "/Aui/slider.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11ce024c").then(next)
    },
  },
  {
    name: "v-7724d8ac",
    path: "/Aui/swiper.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7724d8ac").then(next)
    },
  },
  {
    name: "v-394abf84",
    path: "/Aui/step.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-394abf84").then(next)
    },
  },
  {
    name: "v-df418198",
    path: "/Aui/switch.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-df418198").then(next)
    },
  },
  {
    name: "v-3e913fa0",
    path: "/Aui/tabs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e913fa0").then(next)
    },
  },
  {
    name: "v-f94e15b0",
    path: "/Aui/textarea.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f94e15b0").then(next)
    },
  },
  {
    name: "v-2e0afcb8",
    path: "/Aui/table.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e0afcb8").then(next)
    },
  },
  {
    name: "v-01fc3b7c",
    path: "/Aui/time.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01fc3b7c").then(next)
    },
  },
  {
    name: "v-28dcfdb8",
    path: "/Aui/tag.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28dcfdb8").then(next)
    },
  },
  {
    name: "v-3fd701da",
    path: "/Aui/timeline.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3fd701da").then(next)
    },
  },
  {
    name: "v-1e781dc4",
    path: "/Aui/theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e781dc4").then(next)
    },
  },
  {
    name: "v-7395f644",
    path: "/Aui/tooltip.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7395f644").then(next)
    },
  },
  {
    name: "v-93cfd140",
    path: "/Aui/tree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-93cfd140").then(next)
    },
  },
  {
    name: "v-286279f4",
    path: "/Aui/transfer.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-286279f4").then(next)
    },
  },
  {
    name: "v-023825b0",
    path: "/Aui/type.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-023825b0").then(next)
    },
  },
  {
    name: "v-08fa96cc",
    path: "/Aui/upload.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08fa96cc").then(next)
    },
  },
  {
    name: "v-853ee47e",
    path: "/Sdk/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-853ee47e").then(next)
    },
  },
  {
    path: "/Sdk/index.html",
    redirect: "/Sdk/"
  },
  {
    name: "v-c45cdc7c",
    path: "/Sdk/ab-logger-upload.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c45cdc7c").then(next)
    },
  },
  {
    name: "v-04e3086a",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04e3086a").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-1a06bd78",
    path: "/Sdk/ab-logger.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a06bd78").then(next)
    },
  },
  {
    name: "v-543b261a",
    path: "/Sdk/ab-manager-auf.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-543b261a").then(next)
    },
  },
  {
    name: "v-46ab2252",
    path: "/Sdk/ab-manager-burypoint.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46ab2252").then(next)
    },
  },
  {
    name: "v-c696f938",
    path: "/Sdk/ab-manager-communication-iframe.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c696f938").then(next)
    },
  },
  {
    name: "v-cf6104dc",
    path: "/Sdk/ab-manager-codec.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cf6104dc").then(next)
    },
  },
  {
    name: "v-31885064",
    path: "/Sdk/ab-manager-database.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31885064").then(next)
    },
  },
  {
    name: "v-2c014f78",
    path: "/Sdk/ab-manager-data.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c014f78").then(next)
    },
  },
  {
    name: "v-54ea7178",
    path: "/Sdk/ab-manager-eventbus.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54ea7178").then(next)
    },
  },
  {
    name: "v-29a54784",
    path: "/Sdk/ab-manager-device.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-29a54784").then(next)
    },
  },
  {
    name: "v-44b1d004",
    path: "/Sdk/ab-manager-hotkey.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44b1d004").then(next)
    },
  },
  {
    name: "v-0cdb4118",
    path: "/Sdk/ab-manager-hotload.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0cdb4118").then(next)
    },
  },
  {
    name: "v-557ecb04",
    path: "/Sdk/ab-manager-focus2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-557ecb04").then(next)
    },
  },
  {
    name: "v-3314c5e4",
    path: "/Sdk/ab-manager-page.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3314c5e4").then(next)
    },
  },
  {
    name: "v-09faba14",
    path: "/Sdk/ab-manager-service.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09faba14").then(next)
    },
  },
  {
    name: "v-67183588",
    path: "/Sdk/ab-manager-storage.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67183588").then(next)
    },
  },
  {
    name: "v-01604676",
    path: "/Sdk/ab-manager-trade.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01604676").then(next)
    },
  },
  {
    name: "v-1e758abc",
    path: "/Sdk/ab-manager-store.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e758abc").then(next)
    },
  },
  {
    name: "v-6cc1d93a",
    path: "/Sdk/ab-manager-trade-track.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6cc1d93a").then(next)
    },
  },
  {
    name: "v-34123814",
    path: "/Sdk/ab-manager-watermark.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34123814").then(next)
    },
  },
  {
    name: "v-bf134920",
    path: "/Sdk/ab-manager-websocket.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bf134920").then(next)
    },
  },
  {
    name: "v-b4ad65f8",
    path: "/Sdk/ab-plugin-burypoint.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b4ad65f8").then(next)
    },
  },
  {
    name: "v-b221b2b8",
    path: "/Sdk/ab-plugin-aft.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b221b2b8").then(next)
    },
  },
  {
    name: "v-fe115838",
    path: "/Sdk/ab-plugin-codec-file.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fe115838").then(next)
    },
  },
  {
    name: "v-292521f4",
    path: "/Sdk/ab-plugin-client.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-292521f4").then(next)
    },
  },
  {
    name: "v-484ffdb8",
    path: "/Sdk/ab-plugin-customize.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-484ffdb8").then(next)
    },
  },
  {
    name: "v-0d1a71ca",
    path: "/Sdk/ab-plugin-communication-bridge.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d1a71ca").then(next)
    },
  },
  {
    name: "v-271a1b9e",
    path: "/Sdk/ab-plugin-device.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-271a1b9e").then(next)
    },
  },
  {
    name: "v-95aa98b8",
    path: "/Sdk/ab-plugin-embed-scrcu-jieao.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-95aa98b8").then(next)
    },
  },
  {
    name: "v-4f4cc4b8",
    path: "/Sdk/ab-plugin-embed-scrcu-oleie.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f4cc4b8").then(next)
    },
  },
  {
    name: "v-57ce5644",
    path: "/Sdk/ab-plugin-embed-spdb-topcheer.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-57ce5644").then(next)
    },
  },
  {
    name: "v-37013fa4",
    path: "/Sdk/ab-plugin-embed-xinwanjia.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37013fa4").then(next)
    },
  },
  {
    name: "v-15fc8df8",
    path: "/Sdk/ab-plugin-embed-sunyard.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15fc8df8").then(next)
    },
  },
  {
    name: "v-0c21acc4",
    path: "/Sdk/ab-plugin-evs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c21acc4").then(next)
    },
  },
  {
    name: "v-185f1038",
    path: "/Sdk/ab-plugin-embed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-185f1038").then(next)
    },
  },
  {
    name: "v-307ac6bc",
    path: "/Sdk/ab-plugin-keyboard.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-307ac6bc").then(next)
    },
  },
  {
    name: "v-7f070792",
    path: "/Sdk/ab-plugin-file.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f070792").then(next)
    },
  },
  {
    name: "v-2c153204",
    path: "/Sdk/ab-plugin-liveness.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c153204").then(next)
    },
  },
  {
    name: "v-0bc50490",
    path: "/Sdk/ab-plugin-pinyin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0bc50490").then(next)
    },
  },
  {
    name: "v-c8560698",
    path: "/Sdk/ab-plugin-notification.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c8560698").then(next)
    },
  },
  {
    name: "v-1ff48f78",
    path: "/Sdk/ab-plugin-media.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ff48f78").then(next)
    },
  },
  {
    name: "v-35e54fc6",
    path: "/Sdk/ab-plugin-peer.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35e54fc6").then(next)
    },
  },
  {
    name: "v-9f7bf564",
    path: "/Sdk/ab-plugin-vt.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9f7bf564").then(next)
    },
  },
  {
    name: "v-173439c4",
    path: "/Sdk/ab-plugin-trade-track.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-173439c4").then(next)
    },
  },
  {
    name: "v-2f385224",
    path: "/Sdk/ab-plugin-tools.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f385224").then(next)
    },
  },
  {
    name: "v-aa9d2f78",
    path: "/Sdk/ab-plugin-trade.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aa9d2f78").then(next)
    },
  },
  {
    name: "v-2bdf89f6",
    path: "/Sdk/ab-plugin-window-message.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2bdf89f6").then(next)
    },
  },
  {
    name: "v-09b5222c",
    path: "/Sdk/ab-plugin-window.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09b5222c").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]